### ISSUE TITLE
css缺失

### ISSUE THREAD

**Issue by hei-hei-hei-hei** [JaxsonWang/Ghost-Theme#1]
你好，请问
![image](https://github.com/user-attachments/assets/bc5fd9a5-b1cf-4380-8883-3b291bab2d72)是因为资源没有上传吗，如果是的话，不知能否获取一份，谢谢

**Comment by JaxsonWang** [comment]
需要 node.js 环境来编译主题：
```bash
npm install
npm run build
```

编译好了目录下有个.zip 文件就是你想要的。

你也可以用已经编译好的主题。

[brave.zip](https://github.com/user-attachments/files/17594574/brave.zip)

**Comment by hei-hei-hei-hei** [comment]
收到，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月1日(周五) 上午8:40
收件人: ***@***.***&gt;;
抄送: "Yifan ***@***.******@***.***&gt;;
主题: Re: [JaxsonWang/Ghost-Theme] css缺失 (Issue #1)




 
需要 node.js 环境来编译主题：
 npm install npm run build
 
编译好了目录下有个.zip 文件就是你想要的。
 
你也可以用已经编译好的主题。
 
brave.zip
